app:
  version: @project.version@
spring:
  application:
    name: api
    description: API para sistema de gerenciamento de estoque
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/ProjetoIntegrador}
    username: ${DATASOURCE_USERNAME:ProjetoIntegrador_APPL}
    password: ${DATASOURCE_PASSWORD:ProjetoIntegrador_APPL}
  jpa:
    hibernate:
      ddl-auto: validate
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
  error:
    include-message: always
management:
  server:
    port: 9090
  endpoint:
    health:
      show-details: always
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE