version: '3.9'
services:
  mysql:
    container_name: 'projeto_integrador-db'
    command: '--default-authentication-plugin=mysql_native_password'
    image: 'mysql:8-debian'
    ports:
      - "3306:3306"
    volumes:
      - './sql:/docker-entrypoint-initdb.d'
      - 'data-mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'ProjetoIntegrador'
      MYSQL_USER: 'ProjetoIntegrador_APPL'
      MYSQL_PASSWORD: 'ProjetoIntegrador_APPL'
volumes:
  data-mysql: